"""Stress-test the full pipeline (anti-spoof + speaker verification + fusion).

Scores every wav in samples/stress/ against the enrollment reference
samples/stress/real_enroll.wav using the same code path as the API's
_score_chunk (models.anti_spoof -> models.speaker -> risk.fusion), so the
numbers here are the numbers the demo server would send to the frontend.

Prints a full table AND writes samples/stress/RESULTS.md with:
  raw AASIST bonafide logit, spoof_risk, ECAPA similarity, speaker_mismatch,
  fused risk_score, flags, alert, expected outcome, pass/fail.

Usage:  python stress_test.py
"""

import glob
import os
import time

from models import anti_spoof, speaker
from risk.fusion import compute_risk

STRESS_DIR = os.path.join("samples", "stress")
ENROLL = os.path.join(STRESS_DIR, "real_enroll.wav")

# What each sample IS (ground truth) and what the pipeline SHOULD say.
# real  = genuine human, enrolled speaker        -> no alert
# tts   = neural synthesis (stand-in for clone)  -> ALERT
# far/babble may legitimately raise mismatch; they must NOT alert.
EXPECT_ALERT = {
    "real_": False,
    "tts_": True,
}


def score_one(wav_path, enroll_path):
    """Identical to api/routes.py _score_chunk, minus the debug rounding."""
    scored = anti_spoof.score_audio(wav_path)
    spoof_risk = scored["spoof_risk"]  # ensemble: max over available models
    similarity = speaker.verify_speaker(enroll_path, wav_path)["similarity_score"]
    speaker_mismatch = min(1.0, max(0.0, 1 - similarity))
    risk = compute_risk(spoof_risk=spoof_risk, speaker_mismatch=speaker_mismatch)
    return {
        "aasist_logit": scored["aasist_logit"],
        "w2v2_logit": scored["w2v2_logit"],
        "spoof_risk": spoof_risk,
        "similarity": similarity,
        "speaker_mismatch": speaker_mismatch,
        "risk_score": risk["risk_score"],
        "flags": risk["flags"],
        "alert": risk["alert"],
    }


def main():
    wavs = sorted(glob.glob(os.path.join(STRESS_DIR, "*.wav")))
    wavs = [w for w in wavs if not os.path.basename(w).startswith("real_enroll")]

    rows = []
    t0 = time.time()
    for w in wavs:
        name = os.path.basename(w)
        r = score_one(w, ENROLL)
        expected_alert = next((v for k, v in EXPECT_ALERT.items() if name.startswith(k)), None)
        r["expected_alert"] = expected_alert
        r["pass"] = (expected_alert is None) or (r["alert"] == expected_alert)
        rows.append((name, r))
        a = r["aasist_logit"]
        w = r["w2v2_logit"]
        fmt = lambda v: "   n/a " if v is None else f"{v:+7.3f}"
        print(f"{name:30s} aasist{fmt(a)} w2v2{fmt(w)}  spoof {r['spoof_risk']:.3f}  "
              f"mism {r['speaker_mismatch']:.3f}  "
              f"risk {r['risk_score']:5.1f}  alert={r['alert']!s:5s}  "
              f"{'PASS' if r['pass'] else 'FAIL'}  {','.join(r['flags'])}")
    print(f"\n{len(rows)} samples scored in {time.time() - t0:.1f}s")

    fails = [(n, r) for n, r in rows if not r["pass"]]
    print(f"failures: {len(fails)}/{len(rows)}")
    for n, r in fails:
        print(f"  FAIL {n}: got alert={r['alert']}, expected {r['expected_alert']} "
              f"(aasist {r['aasist_logit']:+.2f}, w2v2 {r['w2v2_logit']:+.2f}, "
              f"spoof {r['spoof_risk']:.3f}, "
              f"mism {r['speaker_mismatch']:.3f}, risk {r['risk_score']})")

    # ---- durable log ----
    with open(os.path.join(STRESS_DIR, "RESULTS.md"), "w", encoding="utf-8") as f:
        f.write("# Stress-test raw scores (generated by stress_test.py)\n\n")
        f.write("| sample | AASIST logit | W2V2 logit | spoof_risk | mismatch | risk_score | flags | alert | expected | verdict |\n")
        f.write("|---|---|---|---|---|---|---|---|---|---|\n")
        for n, r in rows:
            f.write(f"| {n} | {r['aasist_logit']:+.3f} | {r['w2v2_logit']:+.3f} | "
                    f"{r['spoof_risk']:.3f} | {r['speaker_mismatch']:.3f} | "
                    f"{r['risk_score']} | {','.join(r['flags']) or '-'} | "
                    f"{r['alert']} | {'alert' if r['expected_alert'] else 'no alert'} | "
                    f"{'PASS' if r['pass'] else 'FAIL'} |\n")
    print(f"table written to {os.path.join(STRESS_DIR, 'RESULTS.md')}")


if __name__ == "__main__":
    main()
